### ISSUE TITLE
Dark Mode is Not Working

### ISSUE THREAD

**Issue by shivam123-dev** [DSC-JSS-NOIDA/QuickLearn#104]
**Describe the bug**
Upon clicking the button just next to Resources button for enabling **dark mode**, it is not working.

**To Reproduce**
1. Go to [website](https://dsc-jss-noida.github.io/QuickLearn/)
2. Click on **Dark Mode Button**

**Expected behavior**
Upon clicking the button, the website should appear in dark mode. But it is still remaining in light mode

**Screenshot**
![image](https://user-images.githubusercontent.com/81038095/155884286-00c86cd5-fe84-4656-a0e4-6bdd23b9e56d.png)

**Desktop**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 98.0.1108.62 (Official build) (64-bit)

**Comment by shivam123-dev** [comment]
Being a GSSOC'22 participant, kindly assign this task of bug fixing to me so that I can start working on it from 1st March.

**Comment by singhkunal01** [comment]
Hey Sir,
Can You assign this task for me ?
So that i can solve this error ?

**Comment by sulogna2001** [comment]
Hey Can I work on this issue for GSsoc22

**Comment by Anish1411** [comment]
hei , i would like to work to work on this , assign it to me

**Comment by adityabhatia17** [comment]
Hey, I think I can solve this issue please assign.

**Comment by A-K-2001** [comment]
Hello,
I am a GSSOC 2022 participant. I can fix this issue. SO, i request you to assign this work to me.
Thank you.

**Comment by Susmita-Dey** [comment]
I am a GSSOC 2022 participant. I can fix this issue. So, I request you to assign this work to me.
Thank you.

**Comment by flow6979** [comment]
Hey, GSSOC'22 participant here, please assign this task to me.
Thank you.

**Comment by bhumithakur** [comment]
If it's not assign to anyone can i work on it @shivam123-dev

**Comment by AMAN123956** [comment]
@shivam123-dev you can work on resolving this issue
