### ISSUE TITLE
Issue Regarding the number of website links given for cpp immediate level

### ISSUE THREAD

**Issue by jaisinha** [DSC-JSS-NOIDA/QuickLearn#105]
Issue Regarding the number of website links given for CPP immediate level

Solution
Adding more good links that are personally recommended by me.As an immediate to advance level coder

links and screenshots 

Websites like-:https://www.youtube.com/c/fitcoder
https://www.google.com/searchq=aditya+verma&oq=aditya+verma&aqs=chrome..69i57j46i19j0i19l8.7494j0j4&sourceid=chrome&ie=UTF-8

**Comment by jaisinha** [comment]
This will really help  students who are looking forward to master cpp

**Comment by HarshKumarChoudary** [comment]
I'm participating in GSSOC'22. Is this task available for that.
please assign it to me.

**Comment by jaisinha** [comment]
@HarshKumarChoudary  I am raising this issue as am a contributor not a mentor.

**Comment by HarshKumarChoudary** [comment]
Ok

**Comment by AMAN123956** [comment]
@jaisinha u can work on this issue
