### ISSUE TITLE
Add resources for JavaScript

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [DSC-JSS-NOIDA/QuickLearn#106]
Hello, I'm a GSSo'C 22 Contributor, Please assign me this issue tomorrow
I will add JavaScript resources related to Programming

**Comment by kunarkrawat** [comment]
Hey I would like to work on this issue

**Comment by gurjeetsinghvirdee** [comment]
> Hey I would like to work on this issue

Please make your own issues don't comment on others and by the way how can you contribute there is no PA in discord and mentors don't have access to this repo
