### ISSUE TITLE
 Cards under Resources section get distorted and overlap when the screen size is altered(Not Responsive)

### ISSUE THREAD

**Issue by SupriyaKumari08** [DSC-JSS-NOIDA/QuickLearn#107]
**Describe the bug**
When we change the size of the screen , at few points the cards overlap, before they finally wrap themselves in .

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to: https://dsc-jss-noida.github.io/QuickLearn/index.html
2. Click on: Explore Resources
3. Click on : Category {select any category from the list}
3. Select any course {example: Web Development -> Frontend}
4. Exit the full screen of the window and go to the edge of your browser
5. Try to change the size of the screen and see the card getting piled up on each other.

**Expected behaviour**
The cards should change their size and adjust according to the window size and then after a certain breakpoint shouldn't pile over one another.

**Screenshots**
<img width="712" alt="Quick Learn ss" src="https://user-images.githubusercontent.com/84588360/156040413-230cb9e2-6f70-4c02-974c-f01e1c2a4d33.png">

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Chrome
 - Version: 98.0.4758.102 (Official Build) (64-bit)
 

**Additional context**
I would like to work on this issue , Kindly Assign it to me.
(GSSoC’22 Contributor)

**Comment by Varinder-KM** [comment]
I had fixed this issue So, can I make PR ?

**Comment by Abh1shekSingh** [comment]
It is still not responsive. Can I work on this issue please. @SupriyaKumari08 Please assign it to me

**Comment by Varinder-KM** [comment]
It is still not responsive because my PR is not merged.

**Comment by Abh1shekSingh** [comment]
Okay

**Comment by the-macson** [comment]
Issue was fixed
