### ISSUE TITLE
Navbar UI

### ISSUE THREAD

**Issue by ankita-das-26** [DSC-JSS-NOIDA/QuickLearn#109]
Navbar can have more columns like testimonials, Offer on Courses etc.

**Comment by geethika1129** [comment]
I am a GSSoC participant and I would like to work on this . Could you please assign this to me.

**Comment by ShambhaviDixit09** [comment]
Hello, 
I am a GSSOC 2022 participant. I can fix this issue. SO, i request you to assign this work to me.
Thank you.

**Comment by adi7yashah** [comment]
I  am a GSSOC 2022 Participant and I can fix this issue . I know complete web development please assign this work to me.
Thank you.

**Comment by utkarshnashine** [comment]
Hello Sir,I am a GSSOC'22 participant and I would like to work on this issue.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by the-macson** [comment]
Now we have no plans for testimonials, Offer on Courses etc.
That's why i am closing the issue
Thank you for showing your interest
