### ISSUE TITLE
docs: Adding a Pull Request Template

### ISSUE THREAD

**Issue by Pradumnasaraf** [DSC-JSS-NOIDA/QuickLearn#115]
### Chnages 
- Adding a PR template
- Template path **`.github/PULL_REQUEST_TEMPLATE.md`**

### Template Preview (while creating a PR.)
![Screenshot from 2022-03-01 17-54-32](https://user-images.githubusercontent.com/51878265/156168840-66822d65-3e60-4026-8064-f967d66cf94b.png)

- Contribution towards GSsoc`22, Thank You

**Comment by DishaRawal** [comment]
Hi,
I would like to create a PR template as shown above. I am a GSsoc'22 participant so kindly assign it to me.

**Comment by aytida0606** [comment]
I want to work on this issue.
