### ISSUE TITLE
Enhancement: Add custom scroll bar

### ISSUE THREAD

**Issue by TG922** [DSC-JSS-NOIDA/QuickLearn#135]
### Description

- I want to add custom scroll bar for this website.

### Screenshot

- Please assign me on this issue under GSSOC '22.

![Image](https://user-images.githubusercontent.com/70098839/156434800-e33c950a-f287-4c00-a4c0-7e3fdb5d09c5.PNG)

**Comment by 02prags** [comment]
Hello, 
The default scrollbar does not look nice in dark mode and therefore I would like to add a custom scrollbar to improve the UI.

**Comment by Pranjali-49** [comment]
Hello, I want to work on this issue under GSSOC'22. Please assign me this issue.

**Comment by VedanshiDixit** [comment]
Hey,I would like to work on this issue.
