### ISSUE TITLE
Adding Scroll back to top botton feature

### ISSUE THREAD

**Issue by TG922** [DSC-JSS-NOIDA/QuickLearn#136]
### Description

- I want to add scroll back to top button for this website. 
- This will improve website’s **User Experience(UX)** with an arrow, when a user start scrolling the page. The page smoothly scrolls back to top when the the button is clicked.

### Screenshot

- Please assign me to work for this feature under GSSOC '22.

![Image](https://user-images.githubusercontent.com/70098839/156443562-acb59d1a-f18a-41ae-9f18-35f9fead2756.PNG)

**Comment by NitinSohal** [comment]
Hey Can you assign me this issue for GSSOC '22.

**Comment by YashBawa** [comment]
Hello , This is Yash participant under Gssoc 22 , would like add this feature "Scroll back to top bottom" to this amazing website , I will be using Jquery function ,  an attractive arrow and a simple animation by Jquery i to take the user to the top . 
This will definitely help the user at the website to get a better interface of the website and easily access the social media handles at the bottom as a future scope to make it even more user friendly . 
Hoping to work on the issue soon !!

**Comment by VedanshiDixit** [comment]
Hey,I would like to work on this issue.

**Comment by Keyurchaniyara** [comment]
Hello @TG922 

I am a GSSoC22 contributor. I would love to work on this issue and as soon as I make fevicon for this issue. Please do assign this to me.

ThankYou:)

**Comment by prachi1211** [comment]
Hey, I am GSSOC Contributor. Please assign me this task.

**Comment by YatreeLadani** [comment]
I'm an GSSOc'22 Contributor, please Assign me this task.
