### ISSUE TITLE
Add responsiveness to contact section

### ISSUE THREAD

**Issue by khushigupta123** [DSC-JSS-NOIDA/QuickLearn#141]
**Issue faced**
Currently, the contact section is not responsive making it difficult for users to operate contact section in tablet or mobile screen.

**Improvements suggested**

- [ ] * Alignment of contact section text according to screen size
- [ ] * Better placement of contact form and contact information card for mobile UI
- [ ] * Better placement of submit button
- [ ] * Completely responsive contact section

**Result achieved**
Easy to read and fill contact section in screen size less than laptop

**I am a GSSOC 2022 participant
Kindly assign this issue to me.**

**Comment by ronitrangwani** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by VedanshiDixit** [comment]
Hey,I would like to work on this issue.
