### ISSUE TITLE
Improving the padding of the cards in Features Section and make the features card images rounded to make them look more attractive

### ISSUE THREAD

**Issue by Hritik-Verma41** [DSC-JSS-NOIDA/QuickLearn#142]
The padding inside the features section cards looks dull and less appealing
![Capture2](https://user-images.githubusercontent.com/75332256/156524122-6af6406c-0539-4195-ae2b-47a2a2f07dd1.PNG)
I would like to add some padding and make the card images look rounded the they look more appealing and attractive.
![Capture3](https://user-images.githubusercontent.com/75332256/156524368-98097888-0991-46b4-9a8d-2394c14af973.PNG)
This is how I would like to do this.
Please assign this task to me.

**Comment by roy-shivam** [comment]
i can do this task. please assign me.
