### ISSUE TITLE
Improving user experience of resource navigation.

### ISSUE THREAD

**Issue by A-Spiral-Forge** [DSC-JSS-NOIDA/QuickLearn#145]
**Is your feature request related to a problem? Please describe.**
Yes, this navigation gives a very bad look to the website. Users may get frustrated.

**Describe the solution you'd like**
I want to make the navigation of the resource page more attractive. Also want to add hover and focus animations.

**Describe alternatives you've considered**
Also, we can make a button from which users can open navigation.

**Additional context**
![image](https://user-images.githubusercontent.com/64008676/156560288-50748288-05c3-407b-a813-62b50da4c8f4.png)
There's a design image [RESOURCE.png](https://github.com/DSC-JSS-NOIDA/QuickLearn/blob/main/Design/Screenshots/Resources.png), with this I also make some additional changes.

**Comment by A-Spiral-Forge** [comment]
@vijayyprajapati Please assign this issue to me under GSSOC'22.

**Comment by roy-shivam** [comment]
I want to make the navigation of the resource page more attractive. can u please assign me this for doing my best..
