### ISSUE TITLE
Scroll back to button

### ISSUE THREAD

**Issue by hk2257853** [DSC-JSS-NOIDA/QuickLearn#149]
Can I add a scroll back to top button?
Will be great if this is assign to me under GSSOC 2022.
Thank you.

**Comment by krisha-a** [comment]
A scroll back button would be a nice feature in the page. Please assign me to this task.

**Comment by Pranjali-49** [comment]
I want to work on this issue under GSSOC'22.

**Comment by prachi1211** [comment]
Hey, I am GSSOC Contributor kindly assign this issue to me.

**Comment by Keyurchaniyara** [comment]
Hello @hk2257853 

I am a GSSoC22 contributor. I would love to work on this issue and as soon as I make fevicon for this issue. Please do assign this to me.

ThankYou:)

**Comment by YatreeLadani** [comment]
I'm an GSSOc'22 Contributor, please Assign me this task.

**Comment by prachi1211** [comment]
Hello,
I am GSSOC Contributor. I am delighted to take this task. Assign me this task.

**Comment by pushpanjali-10** [comment]
I'm Contributor in GSSoC22 . Can u assign this to me.

**Comment by Shatakshi-Choudhary** [comment]
Hey there! I want to work on this issue. I am a GSSoC'22 contributor & I will try my best to resolve this issue. Please assign this issue to me.

**Comment by itsmohitnamdeo** [comment]
Hello
I am GSSOC'2 Contributor
I am interested to solve this issue , can you please assign me this task....

**Comment by Sourajita21** [comment]
Hello,
I am a GSSOC'22 contributor.
 I think it will be great if I add a scroll back button can you please assign me this task.
Thanks for your time.
