### ISSUE TITLE
Lower part of page doesn't look good

### ISSUE THREAD

**Issue by hk2257853** [DSC-JSS-NOIDA/QuickLearn#150]
![Screenshot_20220303-224910_Brave](https://user-images.githubusercontent.com/70331405/156617375-9b1edfbb-013d-4144-848d-c3a2e7d8fefe.jpg)

Can I make this part looks better on smartphone? Just a quick fix. Will be great if can be assigned used Gssoc2022. Thank you.

**Comment by AbhaHimani** [comment]
Can I fix this?

**Comment by hk2257853** [comment]
> Can I fix this?

Bro Iam a contributor asking if I can fix this😅.

**Comment by deekshhaa** [comment]
can i fix it?

**Comment by krisha-a** [comment]
Can i get assigned on this task under GSSOC'22,  the contact page doesn't look up to date.

**Comment by Pranjali-49** [comment]
Can you please assign me this issue, I want to work on this under GSSOC'22.

**Comment by roy-shivam** [comment]
Can I get assigned on this task.

**Comment by rucha0702** [comment]
It's already being addressed here #146
