### ISSUE TITLE
Adding resources for python programming

### ISSUE THREAD

**Issue by Vinayakk404** [DSC-JSS-NOIDA/QuickLearn#153]
Hi i am a gssoc'22 contributor i would like to add a beginner friendly resource  that can help the beginner's new to the programming world for python language

**Comment by deekshhaa** [comment]
I will add projects ideas in diffrent level and practice questions for better understanding...
please assign it to me

**Comment by mayank-del** [comment]
I also have good python resources, i also want to contribute in this .

**Comment by rucha0702** [comment]
We do not more resources as of now unless you are introducing new domains. I would suggest you to work on UI changes.
