### ISSUE TITLE
Feature cards loks and hover.

### ISSUE THREAD

**Issue by AdnanMuzavor** [DSC-JSS-NOIDA/QuickLearn#156]
**Describe the bug**
The cards shown under feature should have a cursor type pointer instead of mouse. Image(3rd card) looks intact

**To Reproduce**
1. Go to 'index.html'
3. Scroll down to 'features card part'
4. See error and fix by adding necessary CSS in given classes.

**Expected behavior**

->When user hovers on card, mouse should turn to pointer
->Will look cool if some padding is introduce as there are just two cards in row.
->Can add some color feeling effects for cards(color in contrast with website
**Screenshots**
recording link: https://www.recordjoy.com/view/VRFRF8hXFKeKNWdsnYqs

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser ->chrome,
 - Version ->

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 9
 - Browser Chrome

**Additional context**
I mentioned most above.

**Comment by Neha9849** [comment]
I would like to work on this :)

**Comment by Neha9849** [comment]
That cards are not links they are just mentioning the features. So i think there is no point of making the cursor pointer.

**Comment by AMAN123956** [comment]
@AdnanMuzavor there is no need for this right now
So I am closing this issue for now
