### ISSUE TITLE
Feature : Adding Sticky Header

### ISSUE THREAD

**Issue by TG922** [DSC-JSS-NOIDA/QuickLearn#158]
### Description

- I want to add sticky header for this website.
- This feature will help user to easily move to other parts of your website without having to scroll all the way to the very top.
- Please assign me on this feature under GSSOC '22.

**Comment by Tanvi444** [comment]
Can you please assign this issue to me?

**Comment by Himanshi236** [comment]
Hey, the header for this website can be made more attractive and I would like to work on improving it. Can you assign me this issue under GSSOC '22?

**Comment by rucha0702** [comment]
@TG922 go ahead

**Comment by TG922** [comment]
@rucha0702 I'm almost done with the issue I will send PR regarding this tomorrow

**Comment by the-macson** [comment]
Thank you for showing your interest
Work on this issue was done
