### ISSUE TITLE
Enhance the mobile responsiveness of  the home page 

### ISSUE THREAD

**Issue by maura-dev** [DSC-JSS-NOIDA/QuickLearn#159]
The home page needs to look good on mobile, especially the contact  section and button

![Annotation 2022-03-05 043539](https://user-images.githubusercontent.com/67394368/156866257-442c6726-b4b9-431a-97e4-4feae69a74c9.png)
![Annotation 2022-03-05 043454](https://user-images.githubusercontent.com/67394368/156866263-cfe714d8-39fc-4e54-9c27-3b27c6e55e15.png)
s

**Comment by Cypher1002** [comment]
hey , loved the ui design would love to work on the project could it be assigned to me through gssoc will try to implement grid template property to enhance the contact section and also thinking to add a hover effect if it fits with the project

**Comment by Cypher1002** [comment]
i am a beginner to  open source would be my first project so will need some mentor ship also

**Comment by Ankita-singh-05** [comment]
Hello @maura-dev! I want to work in this issue under GSSoC'22. Could you please assign it to me?

**Comment by BhumikaJena** [comment]
Currently the home page and specially the contact section is not responsive making it difficult for the users to user it on small screen.
Therefore, I would like to make some improvements to it  and make it fully responsive.
I am a gssoc'22 participant . I would be glad if u assign this task to me.

**Comment by maura-dev** [comment]
> Currently the home page and specially the contact section is not responsive making it difficult for the users to user it on small screen.
> Therefore, I would like to make some improvements to it and make it fully responsive.
> I am a gssoc'22 participant . I would be glad if u assign this task to me.

**Comment by maura-dev** [comment]
@BhumikaJena  @Ankita-singh-05 @Cypher1002  I am also a contributor to gssoc, that was why I created the issue and it has been assigned to me

**Comment by Ankita-singh-05** [comment]
> @BhumikaJena @Ankita-singh-05 @Cypher1002 I am also a contributor to gssoc, that was why I created the issue and I am also waiting for it to be assigned to me

Okay, Okay!

**Comment by mayank-del** [comment]
Hey @maura-dev! I want to work in this issue under GSSoC'22. Could you please assign it to me?

**Comment by rucha0702** [comment]
@maura-dev assigned it to you. Make sure to pull the code before contributing
