### ISSUE TITLE
In cyber security text are over flow

### ISSUE THREAD

**Issue by iScreenager** [DSC-JSS-NOIDA/QuickLearn#166]
![bug](https://user-images.githubusercontent.com/87562957/157059634-4a8dc85f-3df8-400c-8122-01c793ac6813.PNG)

**Comment by vijayyprajapati** [comment]
ya sure

**Comment by iScreenager** [comment]
sir why you closed this issue?

**Comment by vijayyprajapati** [comment]
Heyy @iScreenager !!!
It is open now.
Please fix the problem.

**Comment by nitishsaini706** [comment]
@vijayyprajapati I fixed this 
@iScreenager Are you working on it or should I push my code and make a pr

**Comment by nitishsaini706** [comment]
@vijayyprajapati I created a pr to fix this issue , you can review it

**Comment by nitishsaini706** [comment]
@iScreenager You didn't merged my pr , can you please review my pr, it fixes the issue #180
