### ISSUE TITLE
Enhancing the Contribution Page in Light-Mode 

### ISSUE THREAD

**Issue by BabyElias** [DSC-JSS-NOIDA/QuickLearn#168]
![Comparison_Collage](https://user-images.githubusercontent.com/95405559/157166260-1aa13d9a-8726-4fa2-b47c-f4b1e3d4b852.jpeg)
The contribution page in the dark mode looks really good because of the color contrast between contents of bold headings and the inside text , but in light mode these changes are not very clear.In my opinion, indentation can help improve the layout to a large extent.

Also, can we update the icons? As all icons are just the same making it monotonous(though the website is wonderfully built and executed).

I am GSSoC'22 contributor and can make these changes if needed.Please assign me this issue.

**Comment by the-macson** [comment]
On this issue work has been done 
Thank you for your suggestions
