### ISSUE TITLE
[Contact Us - Section] Blocking user entering invalid email ID

### ISSUE THREAD

**Issue by VaishnaviDontha** [DSC-JSS-NOIDA/QuickLearn#170]
**Describe the bug**
Blocking user entering invalid email ID

**To Reproduce**
1. Go to 'Contact us' Section
2. Enter details for Name, Email ID, Message
3. Hit 'Submit'

**Expected behavior**
Form is accepting invalid email ID data

**Screenshot**

<img width="800" alt="Screen Shot 2022-03-08 at 11 06 33 AM" src="https://user-images.githubusercontent.com/77274387/157278638-125df5c5-9368-43d5-93d6-01954a58578c.png">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser : Chrome
 - Version : 99.0.4844.51

**Comment by roy-shivam** [comment]
i want to work on this issue by using email filtering.

**Comment by AMAN123956** [comment]
@VaishnaviDontha you can start working in this issue

**Comment by the-macson** [comment]
Any update @VaishnaviDontha

**Comment by the-macson** [comment]
I think this bug is fixed 
Thank you for showing your interest @Tanishka003

**Comment by Tanishka003** [comment]
Ok sir
