### ISSUE TITLE
Dark Theme not working in Resource.html

### ISSUE THREAD

**Issue by SainathPoojary** [DSC-JSS-NOIDA/QuickLearn#172]
**Describe the bug**
Dark Theme is not working on the Resource.html page

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://dsc-jss-noida.github.io/QuickLearn/resource.html
2. Click on the Dark Theme icon at the top right corner
3. Page will not change into the dark mode

**Expected behaviour**
Dark Mode

**Screenshots**
![image](https://user-images.githubusercontent.com/53347682/157401900-82f121f9-1d4a-4992-95af-6feb8fcce1ed.png)

**Desktop:**
 - OS: Linux Mint
 - Browser: Firefox
 - Version 98.0

Hi @deshraj @spyshiv @sehgalayush1 @singhsterabhi @deepti1996 @AMAN123956 👋,
I am a contributor at GSSoC'22.
I want to work on this, please assign it to me.

**Comment by rucha0702** [comment]
This issue was created before and a PR for the same has been merged. But no worries, you can try on something else.
