### ISSUE TITLE
Add resources related to Programming Languages

### ISSUE THREAD

**Issue by AMAN123956** [DSC-JSS-NOIDA/QuickLearn#18]
Resources related to Programming required

**Comment by Devv14** [comment]
Hello, 
I want to work on this issue . Please assign it to me ..

**Comment by AMAN123956** [comment]
@Devv14  u can go ahead

**Comment by Devv14** [comment]
Please review PR #21.

**Comment by UdAyAn123** [comment]
I am looking forward to this issue

**Comment by anish2210** [comment]
Hay @AMAN123956 I am a self-taught programmer and a developer I am a student of mechanical engineering and I have learned everything on my own in the field of web dev and software.
I would like to contribute to helping others to achieve their dreams 😊

**Comment by Payalsahb20220** [comment]
Hello @AMAN123956 sir , I want to work on this issue. Can u please assign me.

**Comment by AMAN123956** [comment]
@anish2210 u can work on this project can u explain how u can improve this project or resolve any issues
