### ISSUE TITLE
social icons appearence in attractive way

### ISSUE THREAD

**Issue by roy-shivam** [DSC-JSS-NOIDA/QuickLearn#181]
i want to improve the apperence of social icons in attractive way.

**Comment by Siddhi-Mundada** [comment]
I would like to work on this for GSSOC'22 .Please assign this to me.

**Comment by the-macson** [comment]
@roy-shivam can you more elaborate what you want to improve

**Comment by itsmohitnamdeo** [comment]
Hello,
I am GSSOC Contributor
I am delighted to do this task  can you please Assign me this...

**Comment by the-macson** [comment]
there are no response from @roy-shivam 
that's why I am going to close this issue
