### ISSUE TITLE
background view modification

### ISSUE THREAD

**Issue by roy-shivam** [DSC-JSS-NOIDA/QuickLearn#182]
**Is your feature request related to a problem? Please describe.**
the background of web pages is very simple.

**Describe the solution you'd like**
I would like to add some animated background according to selected stream.

**Comment by roy-shivam** [comment]
please assign me this task.

**Comment by vijayyprajapati** [comment]
Hey @roy-shivam 
Loved your suggestion but can you please tell us more about what you want to do.

**Comment by the-macson** [comment]
there is no update regarding issue so I am closing this issue
