### ISSUE TITLE
Animation effect on social  media links.

### ISSUE THREAD

**Issue by haritdheer** [DSC-JSS-NOIDA/QuickLearn#183]
Hey @Harshil-Jani ,I want to collaborate on this project under GSSOC '22 . Please assign this project to me.

**Comment by Harshil-Jani** [comment]
I am also contributor ! 
Ping @rucha0702  @AMAN123956.
They are maintainers.

**Comment by Apexshya** [comment]
I am GSSOC '22 participant and I want to work on this issue. Please assign me this project.

**Comment by vijayyprajapati** [comment]
Hey @Harshil-Jani
We have assigned you to the issue. Now you can work on the issue.

**Comment by Yashi2002** [comment]
I am GSSOC '22 participant and I want to work on this issue. Please assign me this project.

**Comment by Dhananjaysharma207** [comment]
I am GSSOC '22 participant and I want to work on this issue as i have recently got the solution of making it more effective. Please assign me this project.

**Comment by rucha0702** [comment]
@haritdheer go ahead

**Comment by aaryahjolia** [comment]
Can I work on this under GSSoC'22 ? 
I will change the icons to circle shape and will add hover effects that will swap the background and fill color when hovered.

**Comment by rucha0702** [comment]
You may work on this @aaryahjolia
