### ISSUE TITLE
Adding link in navbar

### ISSUE THREAD

**Issue by Areebah03** [DSC-JSS-NOIDA/QuickLearn#186]
I want to add a logo and links in navbar for feature, contact and About us section.

**Comment by vijayyprajapati** [comment]
Hey @Areebah03  
Thank you for showing interest in the project. 
We appreciate your suggestion but can you please provide us with more information about the changes you wanted to do.

**Comment by Areebah03** [comment]
Hey @vijayyprajapati 
In want to add a logo in navbar and contents like About us  feature, contact us that will scroll down to particular section.

**Comment by jagadeeshvr** [comment]
Hello @vijayyprajapati 
I'm Contributer in GSSoC22,Can u assign this to me.I will create responsive nav bar by adding home screen link,suport link,help link and contact us and next pages link in nav bar itself

**Comment by the-macson** [comment]
@vijayyprajapati please review this issue.

**Comment by Sourajita21** [comment]
Hello sir,
I am a GSSOC contributor. Can you please assign me this task. I will add a responsive nav bar and other features too and if you find any problem in my work then I will rectify as soon as possible. Please assign me this task. Thanks for your time.
