### ISSUE TITLE
Text not visible clearly in Dark Mode.

### ISSUE THREAD

**Issue by ABHID10** [DSC-JSS-NOIDA/QuickLearn#187]
**Describe the bug**
Text color not visible clearly in Dark Mode on https://dsc-jss-noida.github.io/QuickLearn/

**To Reproduce**
1. Go to 'https://dsc-jss-noida.github.io/QuickLearn/'
2. Click on 'Dark - Mode button'
3. Scroll down to 'Hackfest @GDSC- Main Paragraph'

**Expected behavior**
Main paragraph text should be visible clearly to the users.

**Screenshots**
![image](https://user-images.githubusercontent.com/86340981/158028376-015c6893-f112-4337-b913-b07d6cd5af68.png)
![image](https://user-images.githubusercontent.com/86340981/158028391-79b7e942-515a-4672-a6e2-695fb9a52c12.png)

**Desktop :**
 - OS: [Windows-10]
 - Browser [chrome, mozilla firefox ]
 - Version [64-Bit]

**Smartphone :**
 - Device: [One Plus X]
 - OS: [Android]
 - Browser [chrome,stock browser]
 - Version [11]

**Additional context**
Changed Card layout and background.

**Comment by ABHID10** [comment]
GSSoC-22 
Would like to solve this issue !!

**Comment by vijayyprajapati** [comment]
Hey @ABHID10 
Thank you for showing interest in the project.
You have suggested good changes.
We would like you to solve the issue.
