### ISSUE TITLE
improving join us area.

### ISSUE THREAD

**Issue by deepak759** [DSC-JSS-NOIDA/QuickLearn#194]
In join us area, all things are looking messy, and in dark mode it also not looking good.
I want to improve its design  .
I also want to add feature of on clicking  main location it directly open google maps and direction for this, and on clicking mail us it directly open mailing app for mailing  and on clicking contact it directly copy the phone number or if we are in phone it directly open contact app for calling.

I am delighted to work on this feature.

**Comment by paul-111** [comment]
can i get assignned to it

**Comment by pushpanjali-10** [comment]
I'm Contributor in GSSoC22 . Can u assign this to me.

**Comment by the-macson** [comment]
Any update @deepak759

**Comment by deepak759** [comment]
@the-macson yes I am working on this.

**Comment by deepak759** [comment]
@rucha0702 thanks for assigning it to me.

**Comment by the-macson** [comment]
Great @deepak759

**Comment by deepak759** [comment]
@the-macson I make a pull request, but I don't know did I do it in proper way. can you help in finding it.
