### ISSUE TITLE
change Stop Searching Start Learning section in index.html page 

### ISSUE THREAD

**Issue by heyvats21** [DSC-JSS-NOIDA/QuickLearn#195]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by heyvats21** [comment]
Will change design of this section.
I want to work on this issue under GSSOC'22 .

![image](https://user-images.githubusercontent.com/81029204/158736195-8d82aa3e-0208-4031-8359-805b5f161380.png)

**Comment by rucha0702** [comment]
@heyvats21 Any progress here?

**Comment by heyvats21** [comment]
Yeahh i ll update it soon

**Comment by the-macson** [comment]
Ok

**Comment by the-macson** [comment]
Work done on this issue by @nitishsaini706
