### ISSUE TITLE
we need git commands related to upstream and instructions to pull code in the contribution guidelines page

### ISSUE THREAD

**Issue by the-macson** [DSC-JSS-NOIDA/QuickLearn#200]
changes required here: 
![image](https://user-images.githubusercontent.com/77936051/159134192-3c8ba796-11e6-4f94-bb34-42937a04d4f3.png)

**Comment by aytida0606** [comment]
i want work on this issue.

**Comment by aytida0606** [comment]
added upstream commands #201

**Comment by the-macson** [comment]
@aytida0606 I assigned issue to you 
You can start work on this issue

**Comment by the-macson** [comment]
In this issues worked is done 
That's why i am closing the issue
