### ISSUE TITLE
Improving the feature section

### ISSUE THREAD

**Issue by Sandhya312** [DSC-JSS-NOIDA/QuickLearn#202]
**Description**
The size of the card is not equal in the feature section.

**Screenshots**
![FeatureSection](https://user-images.githubusercontent.com/85842071/159135599-c3ab3fe1-5260-49da-9413-5f9a5b2f6bac.png)

**Comment by Sandhya312** [comment]
I am a GSSOC'22 contributor.
I want to work on this project. Please assign it to me.

**Comment by khushbubijawat** [comment]
I am a GSSOC'22 contributor.
I want to work on this project. Please assign it to me.

**Comment by AMAN123956** [comment]
@Sandhya312 any updates?
