### ISSUE TITLE
change thumbnail for sections inside Categories .

### ISSUE THREAD

**Issue by wre9-tesh** [DSC-JSS-NOIDA/QuickLearn#203]
I think we should change the thumbnail in sections inside Categories to better match the overall color scheme of the page
![image](https://user-images.githubusercontent.com/96977189/159173129-81f725dd-53a0-446d-8ed6-368fb1892723.png)
maybe like this

**Comment by wre9-tesh** [comment]
i am a gssoc participant ,can i take this issue?

**Comment by AMAN123956** [comment]
@wre9-tesh  u can work on this issue

**Comment by the-macson** [comment]
work has been done by @wre9-tesh on this issue.
Good work bro
