### ISSUE TITLE
Improve the styling of buttons under categories

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [DSC-JSS-NOIDA/QuickLearn#212]
I want to enhance the styling of buttons that are under the categories section.The shape and alignment does not looks good when a user visit that page .
![butt](https://user-images.githubusercontent.com/89297894/160254546-0ca4f5cc-6e23-4395-84a8-0b9fddecb907.png)

**Additional context**

**Comment by rucha0702** [comment]
Describe the changes @AsmaIbrahimButt

**Comment by AsmaIbrahimButt** [comment]
Hi @rucha0702 I would improve the shape of button and  the margin .The width of that div in which these button are located should be changed a bit.

**Comment by rucha0702** [comment]
@AsmaIbrahimButt I think the buttons look fine but you can work on improving the border of options when we click the button. The hover effect looks good, keep the same for onclick, remove the border. Can you do that?

![image](https://user-images.githubusercontent.com/77936051/161409550-de8cce2f-90c9-432b-8aa3-226178cd7e76.png)

**Comment by AsmaIbrahimButt** [comment]
Yeah, Kindly assign me.I would like to fix it.

**Comment by AsmaIbrahimButt** [comment]
Hi @rucha0702 Would appreciate to have a review on this pull request  https://github.com/DSC-JSS-NOIDA/QuickLearn/pull/252.THanks
