### ISSUE TITLE
Feature : Adding Scroll back to top button matching theme of website

### ISSUE THREAD

**Issue by TG922** [DSC-JSS-NOIDA/QuickLearn#214]
## Description

- I would like to add a scroll back to the top button that matches the theme of the website.
- I have already worked on it will send PR within some time after being assigned.

## Screenshot
![Image55](https://user-images.githubusercontent.com/70098839/160293798-0e7906c8-8007-4c9a-ab17-6fd17f829b36.PNG)

**Comment by rucha0702** [comment]
I think someone is already working on this #177.  Issue will be assigned to you if needed, communicate there.
