### ISSUE TITLE
Feature : Adding Responsive Scroll bar matching theme of website

### ISSUE THREAD

**Issue by TG922** [DSC-JSS-NOIDA/QuickLearn#215]
## Description

- I would like to add a responsive scroll bar matching the theme of the website
- I have already worked on it will send PR within some time after being assigned.

## Screenshot
![Image56](https://user-images.githubusercontent.com/70098839/160295083-9ed1244c-cfd6-46c7-acc4-a56e55b42fb7.PNG)

**Comment by rucha0702** [comment]
Just the theme color(light purple) would be fine. Remove the gradient.
