### ISSUE TITLE
Bug : User can click submit button without Entering (Email/Name/Message) and also User can enter an invalid email ID

### ISSUE THREAD

**Issue by TG922** [DSC-JSS-NOIDA/QuickLearn#216]
**Describe the bug**

- User can click submit button without Entering (Email/Name/Message)
- User can enter an invalid email ID

**To Reproduce**

1. Go to **Contact Us**
2. Enter details **Email/Name/Message**
3. Click on **Submit**

**Expected behavior**

- The form is accepting empty data
- The form is accepting invalid email ID data

-  I can fix it within some hours assign it to me under GSSOC'22

**Screenshots**

![Image57](https://user-images.githubusercontent.com/70098839/160295697-9aa7679b-1cdc-4686-ae10-921041df85ea.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version 99.0.4844.82

**Comment by the-macson** [comment]
Any update regarding progress @TG922

**Comment by TG922** [comment]
Sorry, @the-macson I haven't received earlier any update regarding your comment in the mail.

I was busy in the hackathon and will send PR today.

**Comment by TG922** [comment]
@the-macson I am sending my PR within some minutes
