### ISSUE TITLE
Add See Contribution Guidelines Page 

### ISSUE THREAD

**Issue by prabhxjottsingh** [DSC-JSS-NOIDA/QuickLearn#22]
Hey, I think that `See Contribution Guidelines` button on `index.html` is not working, and `Explore Resources` button is also redirecting user to the `Contribution` section of the `Resouces.html` page, can I work to resolve both of these issues, and if you want me to add a `favicon` I can add that too after designing one, if you agree ??

**Comment by prabhxjottsingh** [comment]
@deshraj Can you pls look into this issue, and assing it to me ??

**Comment by prabhxjottsingh** [comment]
@Devv14  Can you pls look into this issue, and assing it to me ??

**Comment by Devv14** [comment]
Helo, I'm a contributor too so i can't assign. Someone from the gdsc team will look into your issue and get back to you.

**Comment by AMAN123956** [comment]
@prabhxjottsingh explore resource button functionality is fine u can create a separate page for contribution guideline section

**Comment by prabhxjottsingh** [comment]
@Devv14 oh okay my bad!!

@AMAN123956 Okay, I would like to add a separate page for contribution guidelines section, can you please assign this to me ??
