### ISSUE TITLE
Different thumbnails for Video and Documentation resources.

### ISSUE THREAD

**Issue by rucha0702** [DSC-JSS-NOIDA/QuickLearn#221]
**Is your feature request related to a problem? Please describe.**
All resources have the same thumbnail. It would be easier for user to find a resource if they are categorized on the basis of video and documentation.

**Describe the solution you'd like**
We could have a different thumbnail depending upon the type of resource.

**Comment by gurjeetsinghvirdee** [comment]
Assign me

**Comment by mayankesh239** [comment]
Please assign this to me

**Comment by aytida0606** [comment]
I want to work on this issue .

**Comment by rucha0702** [comment]
Are you working on this @mayankesh239?

**Comment by mayankesh239** [comment]
Yes
