### ISSUE TITLE
Can I add value to textarea in contact us like "Enter your message"?

### ISSUE THREAD

**Issue by Ranjana550** [DSC-JSS-NOIDA/QuickLearn#225]
Here, like just how it is been mentioned for name and email id, can we add for the query box as well?

![image](https://user-images.githubusercontent.com/71266173/161229764-038814fc-1457-45a5-a12c-4a5ef7f8a9e3.png)

if yes,  I would like to work on this issue. Kindly assign it to me.

**Comment by Ranjana550** [comment]
>

**Comment by rucha0702** [comment]
Yes, also can you align the content for all fields to the left?

**Comment by Ranjana550** [comment]
> Yes, also can you align the content for all fields to the left?

Sure, I'll do it. Thank you! :)

**Comment by Ranjana550** [comment]
> Yes, also can you align the content for all fields to the left?

Heyy @rucha0702, it's done. I have made a PR as well. You can check it out.
If there are any more changes that need to be done, please let me know.
Thank you! : )
