### ISSUE TITLE
Improve Contact-us page UI

### ISSUE THREAD

**Issue by nik132-eng** [DSC-JSS-NOIDA/QuickLearn#235]
**Is your feature request related to a problem? Please describe.**
It is a very basic page and it should be more attractive and good looking for any customer to contact the company.

![image](https://user-images.githubusercontent.com/77881638/161442159-991418d4-62ab-4842-b454-131cb4e620c0.png)

**Describe the solution you'd like**
I want to enhance it in a better way

**Comment by nik132-eng** [comment]
Please assign me this issue for GSSOC

**Comment by pragatisahoo2001** [comment]
hello I am gssoc22 participant . I would like to enhance the contact us page please assign the work to me.

**Comment by rucha0702** [comment]
@nik132-eng page looks fine, just left align the placeholder in the input fields and the location, email, contact text should also be left aligned. 
You can improve the dark mode for this section

![image](https://user-images.githubusercontent.com/77936051/161685524-c596a3e7-0fa3-4ad4-915c-76b6b0daa898.png)

**Comment by nik132-eng** [comment]
sure @rucha0702  ma'am
