### ISSUE TITLE
Fix Pointer Behavior on Resources Cards

### ISSUE THREAD

**Issue by XZANATOL** [DSC-JSS-NOIDA/QuickLearn#249]
## Issue

Pointer turns into a cursor once I hover on a card which gives an indication that the card is a clickable link. While only the button inside the card is the only clickable element, which gives a lower rate for UX.

## Fix

Make the pointer only changes when hovering on the button, with leaving the rest of animations untouched.

## Demonstration Video

https://user-images.githubusercontent.com/64689436/162526193-0b658352-592f-4113-bd4b-19a041521b48.mp4

Issue made under GSSoC'22 contributions.

**Comment by Mik-27** [comment]
I am a GSSoC Contributor. I would like to work on the issue.

**Comment by the-macson** [comment]
I am assigning to you @XZANATOL

**Comment by Kishandixit** [comment]
I wants to contribute or work on this issue.
