### ISSUE TITLE
Add Info Image animations

### ISSUE THREAD

**Issue by XZANATOL** [DSC-JSS-NOIDA/QuickLearn#266]
**Is your feature request related to a problem? Please describe.**

Info Images are static on a modern styled page, which gives a boring view to the UI (bad UX review rate)

**Describe the solution you'd like**

Add animation to the info images to improve user interactivity and experience when visiting the site, as demonstrated in the video.

https://user-images.githubusercontent.com/64689436/163729176-6aa4ac66-d0d4-423e-8967-76a0ff8beb5d.mp4

**Additional context**

Issue made under GSSoC'22 contributions.

**Comment by shivamagarwal2510** [comment]
I have worked on this in my previous project. So, please assign this issue to me.
