### ISSUE TITLE
Readme enhancement

### ISSUE THREAD

**Issue by rucha0702** [DSC-JSS-NOIDA/QuickLearn#268]
**Describe the bug**
1. logo alignment needs to be fixed.
2. Remove the project admin and project mentors section

![image](https://user-images.githubusercontent.com/77936051/164014911-6670f106-b74d-4393-89d0-21d48eb0dd70.png)

**To Reproduce**
 Enlarge the GSSoC label a bit and get the 2 logos side by side: GSSoC on the left, and Hackfest on the right.

**Comment by mdnazisharman2803** [comment]
Presently there is some text with logo.. 
I will work on this issue, but let me know, if you want only logo on both side? 
Or I should let the text in between and fix only logo both the side??? 
I'm good at readme let me know 🙂


![IMG_20220420_083538](https://user-images.githubusercontent.com/98539013/164142245-d5ca295a-340e-4ca3-9a56-c068944447cd.jpg)

**Comment by rucha0702** [comment]
just the logo @mdnazisharman2803

**Comment by mdnazisharman2803** [comment]
@rucha0702  mam is it necessary to fix that image orientation using only html Or i can use css to fix or bootstrap? Kindly let me know.. Mam..

**Comment by the-macson** [comment]
bug is resolved and PR is merged

**Comment by the-macson** [comment]
Good work @mdnazisharman2803
