### ISSUE TITLE
Add lazy loading to images

### ISSUE THREAD

**Issue by XZANATOL** [DSC-JSS-NOIDA/QuickLearn#272]
**Is your feature request related to a problem? Please describe.**

On visiting the website, all the images are loaded without prioritizing those which are in the users viewport. It causes a slow loading of the website in addition to a bad user experience (UX) during his first visit. Also not all users scroll down to the very end of the website, also `in the current state` they are still forced to load all the images in the website which causes delays.

**Describe the solution you'd like**

I would like to add `lazy loading` which is a HTML feature to images where it prioritizes loading images in this order:

1) Images that are in users viewport.
2) Images that are approaching users viewport.
3) **DOES NOT** load other images except if it's approaching the users viewport.

**Additional context**

Issue made under GSSoC'22 contributions.

**Comment by tasneemahmed123** [comment]
Can you assign me this issue
