### ISSUE TITLE
map link using Html 

### ISSUE THREAD

**Issue by Yashashviarora** [DSC-JSS-NOIDA/QuickLearn#274]
In this issue I use a map on which state name are written on clicking upon state name  it will directly take us on a site where details of that state are mentioned.
It will use map area tag

**Comment by tasneemahmed123** [comment]
Hello can you assign me this issue I will try to map link using html

**Comment by Yashashviarora** [comment]
hey @rucha0702 why uhh closed this issue is there any problem in this issue
