### ISSUE TITLE
Instagram link is not working in README file

### ISSUE THREAD

**Issue by Ashish4321-hub** [DSC-JSS-NOIDA/QuickLearn#278]
**Describe the bug**
The link is not working properly .it is not redirected to Instagram

**Expected behavior**
The Instagram I'd should be open when you click the icon of Instagram in readme file
**Smartphone (please complete the following information):**
 - Device: realme narzo
 - Browser chrome

**Comment by kusumita29** [comment]
I would like to work on this issue under GSSoC '22

**Comment by kusumita29** [comment]
> /assign

may I work on this issue? @Ashish4321-hub

**Comment by kusumita29** [comment]
may I work on this issue? @rucha0702
