### ISSUE TITLE
Sidebar is not dark in dark mode

### ISSUE THREAD

**Issue by Adhetya** [DSC-JSS-NOIDA/QuickLearn#289]
**Describe the bug**
Sidebar colour does not become dark in dark mode

**Expected behavior**
Sidebar should match dark mode colour scheme

**Screenshots**
<img width="1440" alt="Screenshot 2022-05-04 at 8 55 23 PM" src="https://user-images.githubusercontent.com/20537150/166715671-a63bd1e4-cf71-4a2e-989a-81aa03744b38.png">

I am GSSOC 22 contributor. Please assign this issue to me

**Comment by vijayyprajapati** [comment]
Go ahead
