### ISSUE TITLE
want to add a password generator website using HTML, CSS & JS in web development section

### ISSUE THREAD

**Issue by TANYA-CHAN** [DSC-JSS-NOIDA/QuickLearn#293]
**Is your feature request related to a problem? Please describe.**
An interactive password generator using HTML, CSS & JS.

**Additional context**
https://tanya-chan.github.io/password-generator/

**Comment by TANYA-CHAN** [comment]
@rucha0702 please assign

**Comment by the-macson** [comment]
@rucha0702 Please review this issue

**Comment by rucha0702** [comment]
This website is for learning resources @TANYA-CHAN

**Comment by TANYA-CHAN** [comment]
Can it be converted into a project idea for making a simple mern project

**Comment by the-illuminatus** [comment]
can I work on this issue?
