### ISSUE TITLE
Default HTML Form validation feedback message present

### ISSUE THREAD

**Issue by udith51** [DSC-JSS-NOIDA/QuickLearn#297]
![image](https://user-images.githubusercontent.com/72927422/168422440-9cc4fcb5-1916-4417-830b-5f5ee35073f3.png)
The default message provided by html looks odd. I want to add a customized message for validation feedback.

Please assign me this issue.

**Comment by udith51** [comment]
@rucha0702

**Comment by shahnehal0407** [comment]
Assign it to me
