### ISSUE TITLE
Add resources for Frontend

### ISSUE THREAD

**Issue by AMAN123956** [DSC-JSS-NOIDA/QuickLearn#3]
Add resources related to frontend web development

**Comment by biohazard2117** [comment]
I will do it @AMAN123956 . But can you be more descriptive about what you want to be done?

**Comment by AMAN123956** [comment]
@biohazard basically I want some resources  (documentation,blog links) related to various topics on front-end web development to be listed down

**Comment by vivekarora-02** [comment]
Hey, there!
I would like to contribute to this issue, can you please assign me?

ThankYou!

**Comment by AMAN123956** [comment]
@biohazard2117  are u interested on working on this issue

**Comment by HimangsKalita** [comment]
Please check pull request #16

**Comment by RitikaGarg-tech** [comment]
Sir can i work on this

**Comment by AMAN123956** [comment]
@RitikaGarg-tech u can work on this

**Comment by srivasPankhuri** [comment]
@AMAN123956  Sir, I would like to contribute to this issue. 
Can I work on it?

**Comment by AMAN123956** [comment]
@srivasPankhuri u can go ahead

**Comment by PreetiBaskey** [comment]
Hello... I am working on React Native Projects and it is a good option to choose as a open-source UI framework. You can assign me the issue for this. And you can discuss the requirements of yours  - project , so that i can work through.

**Comment by akashroy1** [comment]
Hi! Can I work on this?

**Comment by ManaliPawar** [comment]
hello, i am a GSSOC participant, Can i work on this issue?

**Comment by ritikaaaa177** [comment]
hello please assign me this issue . I would like to work upon it

**Comment by Sanghu01** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by sceary-expert** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by ishilpi** [comment]
Hi @AMAN123956 sir,
I am a GSSOC participant.
can you assign this issue to me ?  I would like to work on it.

**Comment by Sakshi-1701** [comment]
Hello @AMAN123956 sir,
I would love to work on this. 
It would be great if you could assign this issue to me.

**Comment by AMAN123956** [comment]
@akashroy1 @Sakshi-1701 @ManaliPawar @Sanghu01 @ritikaaaa177 u all can work on this issue

**Comment by shilpiverma24** [comment]
Hi @AMAN123956 sir,
I am a GSSOC participant.
I would like to work on it.  please assign me this issue.

**Comment by Admiller03** [comment]
Hi. Im a GSSOC participant, can i add some resources ?
