### ISSUE TITLE
Adding resources to AI & ML and Data Science section

### ISSUE THREAD

**Issue by kusumita29** [DSC-JSS-NOIDA/QuickLearn#326]
![Screenshot (665)](https://user-images.githubusercontent.com/99873488/170811250-ebb175ef-c2c7-4801-8df9-4bb552574413.png)
![Screenshot (666)](https://user-images.githubusercontent.com/99873488/170811253-0cb5e28a-8afb-44b9-8807-864a6b54fe7a.png)

The sub-sections created under the category Artificial Intelligence and Data Science have dummy resource links. I want to add some video tutorials, Github repos and documents related to these domains. 

Please assign me this issue. I want to work on it under GSSoC '22. 
@rucha0702

**Comment by rolikaagarwal** [comment]
I'm a GSSoC'23 Contributor. Please assign me this issue.
