### ISSUE TITLE
Doesn't change the color mode icon (dark / light)

### ISSUE THREAD

**Issue by SubhamB2003** [DSC-JSS-NOIDA/QuickLearn#370]
**Describe the bug**
After clicking the dark mode button it doesn't change the icon and the navbar color is not changed.

**Expected behavior**
In dark mode time, the icon should be on the sun or day icon.

**Screenshots**
Light Mode
![image](https://github.com/DSC-JSS-NOIDA/QuickLearn/assets/94003231/e250d713-f862-4618-b86b-40c49b03c0f8)

Dark Mode
![image](https://github.com/DSC-JSS-NOIDA/QuickLearn/assets/94003231/aa6f1dce-e188-4717-96b1-18c29e2822e3)

The icon doesn't change.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by silwite** [comment]
Hello , I would like to work on this issue .Please assign it to me under GSSOC'23
Tech Stack - MERN
