### ISSUE TITLE
Add resources

### ISSUE THREAD

**Issue by sumitkr2000** [DSC-JSS-NOIDA/QuickLearn#410]
**Is your feature request related to a problem? Please describe.**
Yes, I want to add some very useful resources to your nice website. Some of the resources include Sololearn, love Babbar DSA course, strive sde sheet, etc. I have done around 2000+ DSA questions and I know good resources. Please assign me this issue. Thank you!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.I will try to make it as better as possible.Please assign this issue to me.It would be grateful for me to work on it.

**Comment by sumitkr2000** [comment]
@ayushnighoskar i am working on this issue. Please raise another issue. Thank you.

**Comment by sumitkr2000** [comment]
Please assign me this issue.

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it.
