### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by Anant7393** [DSC-JSS-NOIDA/QuickLearn#44]

**Comment by shray-jayn** [comment]
I have added a Favicon 

![favicon](https://user-images.githubusercontent.com/76147471/136361661-d31a8161-d287-4ce2-a89f-3e558223eb06.png)


pls, review and merge pr #54.
Thanks in advance.

**Comment by Ashish4321-hub** [comment]
@Anant7393  I want to add favicon .I have lot of favicon.
pls assign me this issue.

**Comment by Ashish4321-hub** [comment]
@Anant7393  I want to add favicon on this website.
please assign me this issue.

**Comment by AnweshaRoses** [comment]
I am a GSSOC participant, if the issue is still not solved I would love working on it

**Comment by ManaliPawar** [comment]
i would like to work on this issue,can you please assign me? I am a GSSOC participant

**Comment by UdAyAn123** [comment]
I am looking forward to this issue

**Comment by ritikaaaa177** [comment]
i ama gssoc prticipant can you please assign me this issue ?

**Comment by Sanghu01** [comment]
I want to work on this issue under the gssoc 22. i can do it as soon as possible... plz assign me this.

**Comment by Sanghu01** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by saidhanya18** [comment]
could you please this issue to me

**Comment by Keyurchaniyara** [comment]
Hello 

I am a GSSoC22 contributor. I would love to work on this issue and as soon as I make fevicon for this issue. Please do assign this to me.

ThankYou:)

**Comment by prachi1211** [comment]
Hello
I am a Gssoc'22 Contributor. Kindly assign me this task.
Thank You.

**Comment by YatreeLadani** [comment]
I'm an GSSOc'22 Contributor, please Assign me this task.

**Comment by AMAN123956** [comment]
For now current favicon is good enough so I am closing this issue u all can work on other issues that are there
