### ISSUE TITLE
Quick Learn website should link to latest React documentation

### ISSUE THREAD

**Issue by sabhisharma-ise** [DSC-JSS-NOIDA/QuickLearn#440]
Issue: The React documentation added in the QuickLearner website is https://legacy.reactjs.org/docs/getting-started.html. These docs are old and won't be updated. Go to react.dev for the new React docs. This site is no longer updated.

Notes:
![image](https://github.com/DSC-JSS-NOIDA/QuickLearn/assets/100849696/6eae5032-c9a7-42d9-98f1-d3acb18ff4d6)
| *The React documentation at https://legacy.reactjs.org/docs/getting-started.html is no longer updated.* |

![image](https://github.com/DSC-JSS-NOIDA/QuickLearn/assets/100849696/ef3591be-6688-4e3f-8e06-e47d91aa134c)
| *The React documentation at react.dev is the latest and up-to-date documentation.* |

Possible Solutions:

- Update the React documentation link in the QuickLearner website to point to react.dev.
- Remove the React documentation link from the QuickLearner website.

I hope this helps!

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by harmeetsingh11** [comment]
I am a GSSoC'23 contributor. Can I work on this issue?

**Comment by Naincy04** [comment]
Hello, I want to work on this issue under GSSoc'23 as a contributor. Please assign this issue to me.
