### ISSUE TITLE
Improving the Footer Section

### ISSUE THREAD

**Issue by sabhisharma-ise** [DSC-JSS-NOIDA/QuickLearn#444]
**Is your feature request related to a problem? Please describe.**
The social media icon links are not big and quite small.

**Describe the solution you'd like**
Making the social icons links use the surrounding space and look more Aesthetically Pleasing and User Accessible.

**Describe alternatives you've considered**

**Additional context**

**Comment by Adi-21** [comment]
I just love to solve this issue under GSSoC'23 open source contribution
