### ISSUE TITLE
Typo in index.html in the section "Header Section Ends"

### ISSUE THREAD

**Issue by Kalyan-velu** [DSC-JSS-NOIDA/QuickLearn#576]
**Issue Description:**
I have identified a typo in the `index.html` file of the QuickLearn GitHub repository. Specifically, on line 131, the text within the button element should be corrected from "See Contribution Guidlines" to "See Contribution Guidelines".

**Location:** `index.html`, line 131

**Expected Outcome: **
Upon merging the pull request, the typo will be corrected in the QuickLearn repository, ensuring the accuracy of the displayed text within the button element.

**Comment by Lavesh12** [comment]
please assign me this issue
