### ISSUE TITLE
Design a Logo for the website

### ISSUE THREAD

**Issue by bajajanjana** [DSC-JSS-NOIDA/QuickLearn#6]

**Comment by vivekarora-02** [comment]
Hey, there!
I would like to contribute to this issue, can you please assign me?

ThankYou!

**Comment by AMAN123956** [comment]
hey @vivekarora-02 u can go ahead on working on this issue

**Comment by dikshita-jain-13** [comment]
Hey there !
I would like to contribute on this issue and make a logo for this, can you please assign me this task ?
Thankyou :)

**Comment by tishaag098** [comment]
Hey!!
I would like to contribute to this issue, can you please assign me?

**Comment by ShrutiVaishnav28** [comment]
@AMAN123956 can I, with @vivekarora-02 solve this issue? Will you pls assign this project to me?

**Comment by ShambhaviDixit09** [comment]
Hello,
I am a participant to GSSOC 2022. I would be delighted to fix this issue. So I request you to please assign me this work.
Thankyou.

**Comment by Sanghu01** [comment]
I WANT TO WORK IN THIS ISSUE UNDER GSSOC'22.

**Comment by AMAN123956** [comment]
@tishaag098 are u still interested in working on it
