### ISSUE TITLE
Make the site responsive for mobile and tablet screens

### ISSUE THREAD

**Issue by bajajanjana** [DSC-JSS-NOIDA/QuickLearn#7]

**Comment by vivekarora-02** [comment]
Hey, there!
I would like to contribute to this issue, can you please assign me?

ThankYou!

**Comment by bajajanjana** [comment]
Go ahead @vivekarora-02

**Comment by 1ananya3** [comment]
I want to work on this.Can you assign it to me?

**Comment by rashi1405** [comment]
hello , I am a participant of GSSOC'22 , can you assign me this project to work .

**Comment by rohit-raj25** [comment]
Hey!!
I am a GSSOC participant, can you please assign me this issue?

**Comment by Abh1shekSingh** [comment]
Hey I am Gssoc participant @bajajanjana  please assign this issue to me

**Comment by adi7yashah** [comment]
Hey!!
I am a GSSOC participant, can you please assign me this issue?

**Comment by Sanghu01** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by AMAN123956** [comment]
@1ananya3 are u still interested on working in this issue

**Comment by 1ananya3** [comment]
Yeah . I want to work on this .
