### ISSUE TITLE
Add a responsive navigation bar 

### ISSUE THREAD

**Issue by bajajanjana** [DSC-JSS-NOIDA/QuickLearn#8]

**Comment by Pluffy2217** [comment]
What elements do we need to add in Navbar?
Currently I have "Resources", "Contribution Guidelines", "Features" and "Start Learning".
Should I add or remove something?

**Comment by vivekarora-02** [comment]
Hey, there!
I would like to contribute to this issue, can you please assign me?

ThankYou!

**Comment by Priyanshi-Raj** [comment]
Hey , I sent a PR to it .Please review it

**Comment by bajajanjana** [comment]
@Priyanshi-Raj you have improved the resource button at the top. Under this issue, we are expecting a responsive navigation bar with all menu items listed properly. You can still improve that.

**Comment by Priyanshi-Raj** [comment]
@bajajanjana okay! will surely work over it

**Comment by bhavya-vaid** [comment]
@Priyanshi-Raj  Hey! I would like to work on this. Do u want a horiz or a vertical nav bar and what menu items are to be listed?

**Comment by AnweshaRoses** [comment]
Hey! I would like to work on this issue. can you assign it to me ?
Thank you!

**Comment by tishaag098** [comment]
Hey, there!
I would like to contribute to this issue, can you please assign me?

**Comment by ManaliPawar** [comment]
Hey!!
I am GSSOC participant, can you please assign me this issue?

**Comment by kalashvasaniya** [comment]
Hey, I want to work on this issue!

**Comment by anish2210** [comment]
hello, This is a registration/login page              ------               https://stackblitz.com/edit/angular-ivy-iro2sa
I would love to contribute to this org. can you please assign me this  work 😊😊

**Comment by rohit-raj25** [comment]
Hey!!
I am a GSSOC participant, can you please assign me this issue?

**Comment by anish2210** [comment]
Bro I am also a contributer 😀(not a mentor).

**Comment by codervivek5** [comment]
I want to work on this issue. plz assign me

**Comment by flow6979** [comment]
hey, I am comfortable in solving this issue. can you assign it to me?
thank you

**Comment by b-suryaraj** [comment]
Hey, actually I would like to contribute to this issue. Can you please assign it to me?

**Comment by AMAN123956** [comment]
@anish2210 are u still interested in working on this issue
