### ISSUE TITLE
Adding animation on hover over feature cards

### ISSUE THREAD

**Issue by AMAN123956** [DSC-JSS-NOIDA/QuickLearn#81]

**Comment by AMAN123956** [comment]
@samyaksand u can work on this issue

**Comment by AnIkeT126** [comment]
Can I work on this issue as a part of GSSoC'22??

**Comment by Ashish4321-hub** [comment]
I'm gssoc contributor and I want to work on this issue ... please assign me

**Comment by nidhihegde3108** [comment]
Can I work on this issue as a contributor??

**Comment by prer45** [comment]
Can I please work on this issue ?

**Comment by AMAN123956** [comment]
@nidhihegde3108 u can work on this issue
