### ISSUE TITLE
Update contact section ui

### ISSUE THREAD

**Issue by AMAN123956** [DSC-JSS-NOIDA/QuickLearn#87]

**Comment by AnweshaRoses** [comment]
Hello, If no one is working on It then I would love to take up this issue.

**Comment by varisha-025** [comment]
Hello @AMAN123956, I am a participant in GSSOC 2022. If no one is working on It then I would like to know the next steps on this.

**Comment by AMAN123956** [comment]
> Hello, If no one is working on It then I would love to take up this issue.

@AnweshaRoses U can work on this issue

**Comment by AMAN123956** [comment]
> Hello @AMAN123956, I am a participant in GSSOC 2022. If no one is working on It then I would like to know the next steps on this.

@varisha-025  GSSOC 2022 has not started right now but if you want to contribute in this project then u can raise a issue or work on any of the existing issues

**Comment by AnweshaRoses** [comment]
> > Hello, If no one is working on It then I would love to take up this issue.
> 
> @AnweshaRoses U can work on this issue

@AMAN123956 Made changes to the contact section, please check pr#103.
Thank you.

**Comment by harshitab07** [comment]
Hey, I am GSSOC 2022 participant. I would like to make improvements in Contact section UI. If this issue is still unresolved kindly assign me this one.

**Comment by AnweshaRoses** [comment]
@AMAN123956  I have made necessary changes, can you please check pr#103. 
Thank you!

**Comment by Prit33** [comment]
I would like to do some ui change in the site, kindly assign me for GSSOC 2022 contribution.

**Comment by AMAN123956** [comment]
@Prit33 can u tell what kind of changes u are thinking of
